(()=>{"use strict";
const C=window.CB_CONFIG,G=["GEX","CEX","DEX","VEX"],$=id=>document.getElementById(id);
const state={view:"snapshot",bucket:C.defaultBucket,greek:C.defaultGreek,ratpack:null,voltra:[],history:null,playTimer:null,frame:0};
const pc={responsive:true,displaylogo:false,modeBarButtonsToRemove:["lasso2d","select2d"]};
const baseLayout={paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)",font:{color:"#b8c7d8",family:"Inter,system-ui,sans-serif",size:11},margin:{l:56,r:24,t:24,b:48},xaxis:{gridcolor:"rgba(255,255,255,.06)",zerolinecolor:"rgba(255,255,255,.2)"},yaxis:{gridcolor:"rgba(255,255,255,.045)",zerolinecolor:"rgba(255,255,255,.15)"}};
function raw(repo,path,bust=true){const u=`${C.rawBase}/${repo}/main/${path}`;return bust?`${u}?cb=${Date.now()}`:u}
async function ft(u){const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);return r.text()}
async function fj(u){const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);return r.json()}
function csv(t){const p=Papa.parse(t,{header:true,dynamicTyping:true,skipEmptyLines:true});return p.data}
function err(id,msg){$(id).textContent=msg;$(id).classList.remove("hidden")}
function clear(id){$(id).classList.add("hidden");$(id).textContent=""}
function conn(ok,text){$("connectionDot").className=ok===true?"online":ok===false?"error":"";$("connectionText").textContent=text;$("lastRefresh").textContent=`Last refresh ${new Date().toLocaleTimeString()}`}
function fmt(v){const n=Number(v);if(!Number.isFinite(n))return"—";const a=Math.abs(n);if(a>=1e9)return(n/1e9).toFixed(2)+"B";if(a>=1e6)return(n/1e6).toFixed(2)+"M";if(a>=1e3)return(n/1e3).toFixed(1)+"K";return a>=10?n.toFixed(2):n.toFixed(3)}
function initControls(){for(const[k,v]of Object.entries(C.buckets)){const o=document.createElement("option");o.value=k;o.textContent=v.label;$("bucketSelect").appendChild(o)}$("bucketSelect").value=state.bucket;$("greekSelect").value=state.greek}
function buildGaugeCards(){$("gaugeGrid").innerHTML=G.map(g=>`<div class="gauge-card${g===state.greek?" focused":""}" data-g="${g}"><div id="gauge-${g}" class="gauge-chart"></div><div class="gauge-footer"><span>Total <strong id="tot-${g}">—</strong></span><span id="split-${g}">Call — · Put —</span></div></div>`).join("");document.querySelectorAll(".gauge-card").forEach(c=>c.onclick=()=>{$("greekSelect").value=c.dataset.g;state.greek=c.dataset.g;focusChanged()})}
function renderGauge(g,d){const ratio=Number(d?.[`${g}_Ratio`])||0,total=Number(d?.[`${g}_Total`]),call=Number(d?.[`${g}_Call`]),put=Number(d?.[`${g}_Put`]),bound=Math.max(1,Math.ceil(Math.abs(ratio)*1.25*10)/10),pos=ratio>=0;
Plotly.react(`gauge-${g}`,[{type:"indicator",mode:"gauge+number",value:ratio,number:{font:{size:18,color:pos?"#53dc92":"#ff7b83"},valueformat:".3f"},title:{text:`<b>${g}</b> <span style="font-size:9px;color:#8293a8">RATIO</span>`,font:{size:12,color:"#dce8f4"}},gauge:{axis:{range:[-bound,bound],tickfont:{size:7,color:"#718397"}},bar:{color:pos?"#31d17c":"#ff5f68",thickness:.42},bgcolor:"rgba(255,255,255,.025)",borderwidth:0,steps:[{range:[-bound,0],color:"rgba(255,95,104,.08)"},{range:[0,bound],color:"rgba(49,209,124,.07)"}],threshold:{line:{color:"#dce8f4",width:1},thickness:.75,value:0}}}],{paper_bgcolor:"rgba(0,0,0,0)",margin:{l:12,r:12,t:22,b:0},height:79},{...pc,displayModeBar:false});
$(`tot-${g}`).textContent=fmt(total);$(`split-${g}`).textContent=`Call ${fmt(call)} · Put ${fmt(put)}`}
async function loadGauges(){clear("overviewError");try{const d=await fj(raw("RatPack",C.buckets[state.bucket].ratpack));state.ratpack=d;G.forEach(g=>renderGauge(g,d));conn(true,"Live data connected")}catch(e){conn(false,"RatPack unavailable");err("overviewError","Could not load RatPack: "+e.message)}}
function metric(){return{volume:["Call / put volume by strike","call_vol_sum","put_vol_sum","Call volume","Put volume"],oi:["Call / put open interest by strike","call_oi_sum","put_oi_sum","Call OI","Put OI"],adjusted:["Adjusted call / put volume by strike","adj_call_vol","adj_put_vol","Adjusted call","Adjusted put"],totalVolume:["Total volume by strike","total_vol_sum",null,"Total volume",null],adjustedSum:["Adjusted sum by strike","adj_sum",null,"Adjusted sum",null]}[$("snapshotMetric").value]}
function renderVoltra(){const rows=state.voltra.filter(r=>Number.isFinite(Number(r.strikePrice)));if(!rows.length)return;const m=metric(),es=Number(rows.find(r=>Number.isFinite(Number(r["Theo ES"])))?.["Theo ES"]),filtered=Number.isFinite(es)?rows.filter(r=>Math.abs(Number(r.strikePrice)-es)<=500):rows;filtered.sort((a,b)=>Number(a.strikePrice)-Number(b.strikePrice));const y=filtered.map(r=>String(r.strikePrice)),tr=[];$("voltraTitle").textContent=m[0];
if(m[2]){tr.push({type:"bar",orientation:"h",name:m[3],y,x:filtered.map(r=>Number(r[m[1]])||0),marker:{color:"#49a5ff"}});tr.push({type:"bar",orientation:"h",name:m[4],y,x:filtered.map(r=>-Math.abs(Number(r[m[2]])||0)),marker:{color:"#ff6670"}})}else tr.push({type:"bar",orientation:"h",name:m[3],y,x:filtered.map(r=>Number(r[m[1]])||0),marker:{color:"#5ba7ff"}});
Plotly.react("voltraChart",tr,{...baseLayout,barmode:"relative",margin:{l:70,r:20,t:24,b:46},xaxis:{...baseLayout.xaxis,title:{text:m[2]?"Call (+) / Put (-)":"Value",font:{size:10}},tickformat:"~s"},yaxis:{...baseLayout.yaxis,title:{text:"Strike",font:{size:10}},type:"category",categoryorder:"array",categoryarray:y,tickfont:{size:8}},shapes:Number.isFinite(es)?[{type:"line",xref:"paper",x0:0,x1:1,yref:"y",y0:String(Math.round(es/5)*5),y1:String(Math.round(es/5)*5),line:{color:"#f4b942",width:1,dash:"dot"}}]:[]},pc)}
async function loadVoltra(){clear("voltraError");try{state.voltra=csv(await ft(raw("Voltra",C.buckets[state.bucket].voltra)));$("voltraTimestamp").textContent="As of "+(state.voltra.find(r=>r.timestamp)?.timestamp||"latest");renderVoltra()}catch(e){err("voltraError","Could not load Voltra: "+e.message)}}
async function loadVisual(){clear("visualError");const b=C.buckets[state.bucket],file=`${b.visualPrefix}_brent_bs_${state.greek}.html`;$("visualTitle").textContent=`${b.label} ${state.greek}`;$("visualSourceLink").href=`https://github.com/CBCharts/BrentBSVisuals/blob/main/${file}`;$("visualLoading").classList.remove("hidden");$("visualFrame").classList.add("hidden");try{$("visualFrame").srcdoc=await ft(raw("BrentBSVisuals",file));$("visualLoading").classList.add("hidden");$("visualFrame").classList.remove("hidden")}catch(e){$("visualLoading").classList.add("hidden");err("visualError","Could not load BrentBSVisuals: "+e.message)}}
function ymd(v){return String(v||"").replaceAll("-","")}
function hpath(date){return`${date}/brent_bs/${C.buckets[state.bucket].pusherman}`}
function keys(){return[1,2,3,4,5].map(n=>`Call ${state.greek} ${n}`).concat([1,2,3,4,5].map(n=>`Put ${state.greek} ${n}`))}
function history(rows){const map=new Map;for(const r of rows){if(r.Greek!==state.greek||!r.timestamp||!Number.isFinite(Number(r.strikePrice)))continue;if(!map.has(r.timestamp))map.set(r.timestamp,{timestamp:r.timestamp,theo:Number(r["Theo ES"]),ranks:{}});map.get(r.timestamp).ranks[r.Rank]={strike:Number(r.strikePrice),value:Number(r.Value)}}return{frames:[...map.values()].sort((a,b)=>a.timestamp.localeCompare(b.timestamp)),keys:keys()}}
function renderHistory(h){if(!h.frames.length)throw Error("No matching ranked rows found.");const cp=["#4ca7ff","#67b6ff","#82c4ff","#9bd1ff","#b4ddff"],pp=["#ff626d","#ff7a83","#ff929b","#ffabb1","#ffc1c6"],tr=h.keys.map((k,i)=>({type:"scatter",mode:"lines",name:k,x:h.frames.map(f=>f.timestamp),y:h.frames.map(f=>f.ranks[k]?.strike??null),connectgaps:false,line:{width:1.7,color:k.startsWith("Call")?cp[i]:pp[i-5]}}));tr.push({type:"scatter",mode:"lines",name:"Theo ES",x:h.frames.map(f=>f.timestamp),y:h.frames.map(f=>f.theo),line:{color:"#f4b942",width:2,dash:"dot"}});tr.push({type:"scatter",mode:"markers+text",name:"Current",x:[],y:[],text:[],textposition:"middle right",textfont:{size:9,color:"#eef4fb"},marker:{size:8,color:h.keys.map(k=>k.startsWith("Call")?"#49a5ff":"#ff6670")},showlegend:false});
Plotly.react("timelapseChart",tr,{...baseLayout,hovermode:"x unified",margin:{l:64,r:72,t:30,b:55},xaxis:{...baseLayout.xaxis,title:{text:"Time"}},yaxis:{...baseLayout.yaxis,title:{text:"Strike level"},tickformat:",.0f"},legend:{orientation:"h",y:1.08,x:0,font:{size:9}}},pc);$("timelineSlider").max=String(h.frames.length-1);$("timelineSlider").value="0";state.frame=0;updateFrame(0)}
function updateFrame(i){if(!state.history?.frames.length)return;i=Math.max(0,Math.min(Number(i)||0,state.history.frames.length-1));state.frame=i;const f=state.history.frames[i],xs=[],ys=[],txt=[];$("timelineSlider").value=String(i);$("timelineLabel").textContent=f.timestamp;$("frameTheo").textContent=Number.isFinite(f.theo)?`Theo ES ${f.theo.toFixed(2)}`:"Theo ES —";for(const k of state.history.keys){if(f.ranks[k]){xs.push(f.timestamp);ys.push(f.ranks[k].strike);txt.push(k.replace(` ${state.greek} `," "))}}Plotly.restyle("timelapseChart",{x:[xs],y:[ys],text:[txt]},[state.history.keys.length+1]);Plotly.relayout("timelapseChart",{shapes:[{type:"line",x0:f.timestamp,x1:f.timestamp,y0:0,y1:1,yref:"paper",line:{color:"rgba(255,255,255,.24)",width:1,dash:"dot"}}]});$("levelGrid").innerHTML=state.history.keys.map(k=>`<div class="level-chip ${k.startsWith("Call")?"call":"put"}"><div class="rank">${k}</div><div class="strike">${f.ranks[k]?f.ranks[k].strike.toLocaleString():"—"}</div></div>`).join("")}
async function loadHistory(){stop();clear("timelapseError");const date=ymd($("historyDate").value);$("timelineLabel").textContent="Loading session…";try{state.history=history(csv(await ft(raw("pusherman3000",hpath(date),false))));renderHistory(state.history)}catch(e){state.history=null;$("timelineLabel").textContent="Session unavailable";err("timelapseError",`Could not load ${date} ${C.buckets[state.bucket].label} ${state.greek}: ${e.message}`)}}
function play(){if(!state.history?.frames.length)return;if(state.playTimer){stop();return}$("playButton").textContent="❚❚ Pause";state.playTimer=setInterval(()=>updateFrame(state.frame>=state.history.frames.length-1?0:state.frame+1),180)}
function stop(){if(state.playTimer)clearInterval(state.playTimer);state.playTimer=null;$("playButton").textContent="▶ Play"}
function repos(){$("repoGrid").innerHTML=Object.values(C.repos).map(r=>`<a class="repo-card" href="${r.url}" target="_blank" rel="noopener"><div class="panel-kicker">GitHub source</div><h3>${r.name}</h3><p>${r.description}</p><div class="repo-meta"><span>CBCharts/${r.name}</span><span>Open ↗</span></div></a>`).join("")}
async function think(){clear("thinkscriptError");const date=ymd($("thinkscriptDate").value);$("thinkscriptStatus").textContent="Loading…";try{const h=history(csv(await ft(raw("pusherman3000",hpath(date),false)))),f=h.frames.at(-1);if(!f)throw Error("No matching ranked levels.");const out=[`# CBCharts generated ranked levels`,`# Source: ${date} ${C.buckets[state.bucket].label} ${state.greek}`,`# Frame: ${f.timestamp}`,"","input showLabels = yes;",""];for(const k of h.keys){const p=f.ranks[k];if(!p)continue;const v=k.replaceAll(" ","_"),c=k.startsWith("Call")?"Color.GREEN":"Color.RED";out.push(`plot ${v} = ${p.strike};`,`${v}.SetDefaultColor(${c});`,`${v}.SetPaintingStrategy(PaintingStrategy.HORIZONTAL);`,`${v}.SetLineWeight(2);`,"")}if(Number.isFinite(f.theo))out.push(`plot Theo_ES = ${f.theo};`,`Theo_ES.SetDefaultColor(Color.YELLOW);`,`Theo_ES.SetStyle(Curve.SHORT_DASH);`,"");out.push(`AddLabel(showLabels, "${C.buckets[state.bucket].label} ${state.greek} | ${f.timestamp}", Color.LIGHT_GRAY);`);$("thinkscriptOutput").value=out.join("\n");$("thinkscriptStatus").textContent="Generated from "+f.timestamp}catch(e){$("thinkscriptStatus").textContent="Generation failed";err("thinkscriptError","Could not generate ThinkScript: "+e.message)}}
function setView(v){state.view=v;document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===v));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$(`view-${v}`).classList.add("active");$("pageTitle").textContent={snapshot:"Snapshot",timelapse:"Timelapse",repos:"Repo's",thinkscript:"ThinkScript Generator",howto:"How-To"}[v];if(v==="timelapse"&&!state.history)loadHistory()}
async function live(){await Promise.allSettled([loadGauges(),loadVoltra(),loadVisual()])}
async function focusChanged(){document.querySelectorAll(".gauge-card").forEach(c=>c.classList.toggle("focused",c.dataset.g===state.greek));state.history=null;if(state.view==="snapshot")await loadVisual();if(state.view==="timelapse")await loadHistory()}
function wire(){document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>setView(b.dataset.view));$("bucketSelect").onchange=async e=>{state.bucket=e.target.value;state.history=null;await live();if(state.view==="timelapse")await loadHistory()};$("greekSelect").onchange=async e=>{state.greek=e.target.value;await focusChanged()};$("refreshButton").onclick=async()=>{await live();if(state.view==="timelapse")await loadHistory()};$("snapshotMetric").onchange=renderVoltra;$("historyDate").onchange=loadHistory;$("timelineSlider").oninput=e=>{stop();updateFrame(e.target.value)};$("playButton").onclick=play;$("resetButton").onclick=()=>{stop();updateFrame(0)};$("generateThinkscript").onclick=think;$("copyThinkscript").onclick=async()=>{if(!$("thinkscriptOutput").value)return;await navigator.clipboard.writeText($("thinkscriptOutput").value);$("copyThinkscript").textContent="Copied";setTimeout(()=>$("copyThinkscript").textContent="Copy code",1000)}}
async function init(){initControls();buildGaugeCards();repos();wire();conn(null,"Connecting");await live();setInterval(()=>{loadGauges();loadVoltra();if(state.view==="snapshot")loadVisual()},C.refreshMs)}
init();
})();